[package]
name = "openai"
version = "1.0.0-alpha.5"
authors.workspace = true
edition.workspace = true
description = "An unofficial Rust library for the OpenAI API."
documentation.workspace = true
repository.workspace = true
license.workspace = true
keywords = ["ai", "high-level", "machine-learning", "openai", "library"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = "1.0.93"
dotenvy = "0.15.6"
derive_builder = "0.12.0"
reqwest = { version = "0.11.14", features = ["json"] }
serde = { version = "1.0.152", features = ["derive"] }
openai_proc_macros = { path = "openai_proc_macros", version = "1.0.0-alpha.5" }
openai_bootstrap = { path = "openai_bootstrap", version = "1.0.0-alpha.4" }

[dev-dependencies]
tokio = { version = "1.26.0", features = ["full"] }

[build-dependencies]
dotenvy = "0.15.6"

[workspace]
exclude = ["examples"]

[workspace.package]
authors = ["valentinegb"]
documentation = "https://valentinegb.github.io/openai/"
edition = "2021"
repository = "https://github.com/valentinegb/openai"
license = "LGPL-3.0-or-later"
