[package]
name = "completions_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenvy = "0.15"

[dependencies.openai]
path = "../../"

[dependencies.tokio]
version = "1.24"
features = ["full"]